# Faye
production:
  server: "https://immense-shore-76171.herokuapp.com:4443/faye"
  adapter_javascript_url: "https://immense-shore-76171.herokuapp.com:4443/faye/faye.js"
  adapter: "Faye"
  auth_token: <=% ENV["SYNC_AUTH_TOKEN"] %>
  async: true
