# Faye
development:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "jaksdfhkajsdfhaksdfhaskdjf"
  async: true

test:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "socket"
  async: false


production:
  server: "https://stark-bastion-72425.herokuapp.com/faye"
  adapter_javascript_url: "https://stark-bastion-72425.herokuapp.com//faye/faye.js"
  adapter: "Faye"
  auth_token: <=% ENV["SYNC_AUTH_TOKEN"] %>
  async: true
