# Faye
development:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  auth_token: jafbjk9fa9sdf9adufabfdsf
  adapter: "Faye"
  async: true

test:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
  server: "https://immense-shore-76171.herokuapp.com:9292/faye"
  adapter_javascript_url: "https://immense-shore-76171.herokuapp.com:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: <=% ENV["SYNC_AUTH_TOKEN"] %>
  async: true
